services:
  back:
    image: leasagroun/back-image:latest
    environment:
      - CURRENT_ENVIRONMENT=production
    # volumes:
    #   - ./logs:/app/logs
  front:
    image: leasagroun/front-image:latest
    ports:
      - "8080:80"
    environment:
      - WS_BACK_URL=http://back:5000